### ISSUE TITLE
Δεν αποθηκεύει το App ID

### ISSUE THREAD

**Issue by johnnyxid** [eellak/cim-sso-wp-moodle-fb#1]
Στο /wp-admin/options-general.php?page=wp-fb-autoconnect δεν αποθηκεύεται το appid με αποτέλεσμα να μην λειτουργεί το fb login.

**Comment by adimi** [comment]
Αυτό είναι ένα θέμα που αντιμετωπίζεται όταν χρησιμοποιείται το epinoo με τα plugins και το συγκεκριμένο theme. Παρουσιάζεται και σε άλλες περιπτώσεις plugin η μη αποθήκευση κάποιων παραμέτρων. Δε συμβαίνει σε καθαρή εγκατάσταση του wp. Για το epinoo και το wp-fb-autoconnect, το λύσαμε αποθηκεύοντας hard-coded το fb app id στο αρχείο wp-fb-autoconnect/Main.php στη συνάρτηση jfb_output_facebook_init():

```
      window.fbAsyncInit = function()
      {
        FB.init({
            appId: ' fb app id here ',
            status: true,
            ....
      }
```

**Comment by johnnyxid** [comment]
οκ, μπήκε hard-coded αλλά καλό είναι να προστεθεί και στις οδηγίες.

όταν έχουμε κάνει στο wordpress login μέσω facebook μπορώ να συνδέομαι απευθείας και στο moodle με το facebook account μου; πρέπει να μπει κάποιο plugin στο moodle;

**Comment by vchatzigiannakis** [comment]
SSO ανάμεσα σε wordpress  και moodle γίνεται μέσω CAS και είναι ανεξάρτητο από τον τρόπο σύνδεσης στο wordpress. Για παράδειγμα, αν έχω συνδεθεί μέσω Shibboleth στο wordpress, και είμαι ο χρήστης vhatzi του ΕΜΠ, τότε αν επιλέξω να κάνω Login στο Moodle, θα γίνει σύνδεση χωρίς να μου ζητηθεί username/password. Αν δεν υπάρχει ήδη, θα δημιουργηθεί χρήστης vhatzi@ntua.gr στο moodle.

**Comment by johnnyxid** [comment]
ok, απλά ρωτάω αν χρησιμοποιώ το λογοριασμό μου του facebook για να κάνω login, τι πρέπει να κάνω για να λειτουργεί αυτό;

**Comment by vchatzigiannakis** [comment]
Δεν έχει προδιαγραφεί login στο moodle μέσω facebook, SSO ανάμεσα σε wordpress και moodle γίνεται μέσω CAS.
Αν πατήσεις στο "Log in" του moodle θα πάει ο έλεγχος μέσω CAS στο wordpress. Εκεί αν είσαι ήδη συνδεδεμένος μέσω facebook, Shibboleth ή local acount θα γίνει redirect πίσω στο moodle και θα συνδεθείς αυτόματα.

**Comment by tgkarounos** [comment]
Σας παρακαλώ να δούμε χωριστά το profile μάνατζμεντ του μέσου χρήστη όταν
είναι έτοιμο, να ειναι απλό και φιλικό στο μέσο χρήστη.

Θ.

2015-11-23 15:12 GMT+02:00 Angela Dimitriou notifications@github.com:

> Closed #1 https://github.com/eellak/cim-sso-wp-moodle-fb/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eellak/cim-sso-wp-moodle-fb/issues/1#event-472020810.

## 

http://www.eellak.gr/, http://mycontent.ellak.gr/,
http://www.creativecommons.gr, https://opengov.ellak.gr/,
https://opendata.ellak.gr/, http://ma.ellak.gr/,  http://mathe.ellak.gr/
